from frontier.types.base_int_enum import BaseIntEnum


class EventType(BaseIntEnum):
    REQUEST_ARRIVAL = 1
    REQUEST_END = 2
    REPLICA_SCHEDULE = 3
    BATCH_STAGE_END = 4
    CLUSTER_SCHEDULE = 5
    GLOBAL_SCHEDULE = 6
    MOE_READY = 7
    MOE_COLLECTIVE_SCHEDULE = 8
    PREFILL_SYNC = 9
    PREFILL_SYNC_COLLECTIVE = 10
    REPLICA_STAGE_SCHEDULE = 11
    BATCH_STAGE_ARRIVAL = 12
    BATCH_END = 13
    KV_CACHE_TRANSFER_START = 14
    KV_CACHE_TRANSFER_END = 15
    M2N_TRANSFER_START = 16
    M2N_TRANSFER_END = 17
    PERIODIC_SCHEDULE = 18
    EP_ALLTOALL_COMBINE_COLLECTIVE = 19
    EP_ALLTOALL_COMBINE_READY = 20
    CLUSTER_BATCH_END = 21
    GLOBAL_BATCH_END = 22
    DECODE_SYNC = 23
    DECODE_SYNC_COLLECTIVE = 24
    THINKING_ROUND_REQUEUE = 25
    CPU_KV_CACHE_OFFLOAD_START = 26
    CPU_KV_CACHE_OFFLOAD_END = 27
    CPU_KV_CACHE_RESTORE_START = 28
    CPU_KV_CACHE_RESTORE_END = 29
